import { NationAsia } from './constants';
import GameBoard from './gameBoard';

const nodes = [
  { isOcean: true, name: 'arabiansea' },
  { isOcean: true, name: 'bayofbengal' },
  { isOcean: true, name: 'caspiansea' },
  { isOcean: true, name: 'indianocean' },
  { isOcean: true, name: 'javasea' },
  { isOcean: true, name: 'mediterraneansea' },
  { isOcean: true, name: 'okhotsksea' },
  { isOcean: true, name: 'seaofjapan' },
  { isOcean: true, name: 'southchinasea' },
  { isOcean: true, name: 'timorsea' },
  { isOcean: true, name: 'yellowsea' },
  { isOcean: false, name: 'budapest' },
  { isOcean: false, name: 'egypt' },
  { isOcean: false, name: 'sudan' },
  { isOcean: false, name: 'eastafrica' },
  { isOcean: false, name: 'arabia' },
  { isOcean: false, name: 'persia' },
  { isOcean: false, name: 'afghanistan' },
  { isOcean: false, name: 'nepal' },
  { isOcean: false, name: 'burma' },
  { isOcean: false, name: 'malaysia' },
  { isOcean: false, name: 'hongkong' },
  { isOcean: false, name: 'northkorea' },
  { isOcean: false, name: 'southkorea' },
  { isOcean: false, name: 'formosa' },
  { isOcean: false, name: 'manila' },
  { isOcean: false, name: 'davao' },
  { isOcean: false, name: 'newguinea' },
  {
    nation: NationAsia.TR, factoryType: 'shipyard', name: 'constantinople', egress: 'mediterraneansea',
  },
  { nation: NationAsia.TR, factoryType: 'armaments', name: 'angora' },
  {
    nation: NationAsia.TR,
    factoryType: 'armaments',
    name: 'syria',
    isHome: true,
  },
  { nation: NationAsia.TR, factoryType: 'armaments', name: 'armenia' },
  {
    nation: NationAsia.TR,
    factoryType: 'shipyard',
    name: 'iraq',
    isHome: true,
    egress: 'arabiansea',
  },
  {
    nation: NationAsia.RU,
    factoryType: 'shipyard',
    name: 'odessa',
    isHome: true,
    egress: 'mediterraneansea',
  },
  {
    nation: NationAsia.RU, factoryType: 'armaments', name: 'moscow', isHome: true,
  },
  { nation: NationAsia.RU, factoryType: 'armaments', name: 'omsk' },
  { nation: NationAsia.RU, factoryType: 'armaments', name: 'irkutsk' },
  {
    nation: NationAsia.RU,
    factoryType: 'shipyard',
    name: 'vladivostok',
    egress: 'okhotsksea',
  },
  {
    nation: NationAsia.CN,
    factoryType: 'shipyard',
    name: 'shanghai',
    egress: 'yellowsea',
  },
  {
    nation: NationAsia.CN,
    factoryType: 'armaments',
    name: 'canton',
  },
  {
    nation: NationAsia.CN,
    factoryType: 'armaments',
    name: 'peking',
    isHome: true,
  },
  {
    nation: NationAsia.CN, factoryType: 'armaments', name: 'sinkiang', isHome: true,
  },
  {
    nation: NationAsia.CN,
    factoryType: 'armaments',
    name: 'mongolia',
  },
  {
    nation: NationAsia.FR, factoryType: 'armaments', name: 'cambodia', isHome: true,
  },
  { nation: NationAsia.FR, factoryType: 'armaments', name: 'tongking' },
  {
    nation: NationAsia.FR,
    factoryType: 'shipyard',
    name: 'cochin',
    egress: 'javasea',
  },
  {
    nation: NationAsia.FR,
    factoryType: 'shipyard',
    name: 'annam',
    isHome: true,
    egress: 'southchinasea',
  },
  {
    nation: NationAsia.FR,
    factoryType: 'armaments',
    name: 'siam',
  },
  {
    nation: NationAsia.JP,
    factoryType: 'shipyard',
    name: 'kyoto',
    egress: 'seaofjapan',
  },
  {
    nation: NationAsia.JP,
    factoryType: 'shipyard',
    name: 'kyushu',
    egress: 'yellowsea',
  },
  { nation: NationAsia.JP, factoryType: 'armaments', name: 'akita' },
  {
    nation: NationAsia.JP, factoryType: 'shipyard', name: 'otaru', isHome: true, egress: 'okhotsksea',
  },
  {
    nation: NationAsia.JP,
    factoryType: 'shipyard',
    name: 'tokyo',
    isHome: true,
    egress: 'seaofjapan',
  },
  {
    nation: NationAsia.GB,
    factoryType: 'shipyard',
    name: 'madras',
    isHome: true,
    egress: 'indianocean',
  },
  {
    nation: NationAsia.GB, factoryType: 'armaments', name: 'hyderabad', isHome: true,
  },
  {
    nation: NationAsia.GB,
    factoryType: 'armaments',
    name: 'delhi',
  },
  {
    nation: NationAsia.GB, factoryType: 'shipyard', name: 'bengal', egress: 'bayofbengal',
  },
  {
    nation: NationAsia.GB, factoryType: 'shipyard', name: 'bombay', egress: 'arabiansea',
  },
  {
    nation: NationAsia.GE,
    factoryType: 'shipyard',
    name: 'sumatra',
    isHome: true,
    egress: 'bayofbengal',
  },
  {
    nation: NationAsia.GE, factoryType: 'armaments', name: 'sarawak',
  },
  {
    nation: NationAsia.GE,
    factoryType: 'armaments',
    name: 'celebes',
  },
  {
    nation: NationAsia.GE, factoryType: 'shipyard', name: 'java', egress: 'indianocean',
  },
  {
    nation: NationAsia.GE, factoryType: 'shipyard', name: 'borneo', egress: 'javasea', isHome: true,
  },
];

const edges = [
  ['moscow', 'budapest'],
  ['moscow', 'odessa'],
  ['moscow', 'omsk'],
  ['budapest', 'moscow'],
  ['budapest', 'odessa'],
  ['budapest', 'constantinople'],
  ['budapest', 'mediterraneansea'],
  ['constantinople', 'budapest'],
  ['constantinople', 'mediterraneansea'],
  ['constantinople', 'angora'],
  ['mediterraneansea', 'arabiansea'],
  ['mediterraneansea', 'constantinople'],
  ['mediterraneansea', 'budapest'],
  ['mediterraneansea', 'odessa'],
  ['mediterraneansea', 'armenia'],
  ['mediterraneansea', 'angora'],
  ['mediterraneansea', 'syria'],
  ['mediterraneansea', 'egypt'],
  ['egypt', 'mediterraneansea'],
  ['egypt', 'syria'],
  ['egypt', 'sudan'],
  ['egypt', 'arabiansea'],
  ['sudan', 'egypt'],
  ['sudan', 'eastafrica'],
  ['sudan', 'arabiansea'],
  ['sudan', 'indianocean'],
  ['odessa', 'moscow'],
  ['odessa', 'budapest'],
  ['odessa', 'mediterraneansea'],
  ['odessa', 'omsk'],
  ['odessa', 'armenia'],
  ['odessa', 'persia'],
  ['angora', 'constantinople'],
  ['angora', 'mediterraneansea'],
  ['angora', 'armenia'],
  ['armenia', 'odessa'],
  ['armenia', 'persia'],
  ['armenia', 'iraq'],
  ['armenia', 'syria'],
  ['armenia', 'angora'],
  ['armenia', 'mediterraneansea'],
  ['syria', 'mediterraneansea'],
  ['syria', 'armenia'],
  ['syria', 'iraq'],
  ['syria', 'arabia'],
  ['syria', 'egypt'],
  ['iraq', 'armenia'],
  ['iraq', 'persia'],
  ['iraq', 'arabia'],
  ['iraq', 'syria'],
  ['iraq', 'arabiansea'],
  ['arabia', 'syria'],
  ['arabia', 'iraq'],
  ['arabia', 'arabiansea'],
  ['persia', 'odessa'],
  ['persia', 'omsk'],
  ['persia', 'afghanistan'],
  ['persia', 'arabiansea'],
  ['persia', 'iraq'],
  ['persia', 'armenia'],
  ['omsk', 'moscow'],
  ['omsk', 'odessa'],
  ['omsk', 'persia'],
  ['omsk', 'afghanistan'],
  ['omsk', 'sinkiang'],
  ['omsk', 'irkutsk'],
  ['afghanistan', 'persia'],
  ['afghanistan', 'omsk'],
  ['afghanistan', 'sinkiang'],
  ['afghanistan', 'delhi'],
  ['afghanistan', 'arabiansea'],
  ['arabiansea', 'persia'],
  ['arabiansea', 'afghanistan'],
  ['arabiansea', 'delhi'],
  ['arabiansea', 'bombay'],
  ['arabiansea', 'indianocean'],
  ['arabiansea', 'eastafrica'],
  ['arabiansea', 'sudan'],
  ['arabiansea', 'egypt'],
  ['arabiansea', 'syria'],
  ['arabiansea', 'arabia'],
  ['arabiansea', 'iraq'],
  ['eastafrica', 'sudan'],
  ['eastafrica', 'arabiansea'],
  ['eastafrica', 'indianocean'],
  ['indianocean', 'sudan'],
  ['indianocean', 'eastafrica'],
  ['indianocean', 'arabiansea'],
  ['indianocean', 'madras'],
  ['indianocean', 'bayofbengal'],
  ['indianocean', 'sumatra'],
  ['indianocean', 'java'],
  ['indianocean', 'timorsea'],
  ['irkutsk', 'omsk'],
  ['irkutsk', 'mongolia'],
  ['irkutsk', 'vladivostok'],
  ['mongolia', 'irkutsk'],
  ['mongolia', 'vladivostok'],
  ['mongolia', 'northkorea'],
  ['mongolia', 'yellowsea'],
  ['mongolia', 'shanghai'],
  ['mongolia', 'peking'],
  ['mongolia', 'sinkiang'],
  ['sinkiang', 'omsk'],
  ['sinkiang', 'mongolia'],
  ['sinkiang', 'peking'],
  ['sinkiang', 'canton'],
  ['sinkiang', 'burma'],
  ['sinkiang', 'bengal'],
  ['sinkiang', 'nepal'],
  ['sinkiang', 'delhi'],
  ['sinkiang', 'afghanistan'],
  ['delhi', 'afghanistan'],
  ['delhi', 'sinkiang'],
  ['delhi', 'nepal'],
  ['delhi', 'bengal'],
  ['delhi', 'hyderabad'],
  ['delhi', 'bombay'],
  ['delhi', 'arabiansea'],
  ['bombay', 'arabiansea'],
  ['bombay', 'delhi'],
  ['bombay', 'hyderabad'],
  ['bombay', 'madras'],
  ['madras', 'indianocean'],
  ['madras', 'bombay'],
  ['madras', 'hyderabad'],
  ['hyderabad', 'bombay'],
  ['hyderabad', 'delhi'],
  ['hyderabad', 'bengal'],
  ['hyderabad', 'bayofbengal'],
  ['hyderabad', 'madras'],
  ['bengal', 'delhi'],
  ['bengal', 'nepal'],
  ['bengal', 'burma'],
  ['bengal', 'bayofbengal'],
  ['bengal', 'hyderabad'],
  ['nepal', 'delhi'],
  ['nepal', 'sinkiang'],
  ['nepal', 'bengal'],
  ['bayofbengal', 'hyderabad'],
  ['bayofbengal', 'bengal'],
  ['bayofbengal', 'burma'],
  ['bayofbengal', 'malaysia'],
  ['bayofbengal', 'timorsea'],
  ['bayofbengal', 'sumatra'],
  ['bayofbengal', 'indianocean'],
  ['burma', 'sinkiang'],
  ['burma', 'tongking'],
  ['burma', 'malaysia'],
  ['burma', 'bayofbengal'],
  ['burma', 'bengal'],
  ['vladivostok', 'irkutsk'],
  ['vladivostok', 'mongolia'],
  ['vladivostok', 'northkorea'],
  ['vladivostok', 'okhotsksea'],
  ['okhotsksea', 'vladivostok'],
  ['okhotsksea', 'otaru'],
  ['okhotsksea', 'seaofjapan'],
  ['okhotsksea', 'northkorea'],
  ['northkorea', 'vladivostok'],
  ['northkorea', 'okhotsksea'],
  ['northkorea', 'southkorea'],
  ['northkorea', 'mongolia'],
  ['southkorea', 'northkorea'],
  ['southkorea', 'seaofjapan'],
  ['southkorea', 'yellowsea'],
  ['otaru', 'okhotsksea'],
  ['otaru', 'akita'],
  ['akita', 'otaru'],
  ['akita', 'seaofjapan'],
  ['akita', 'tokyo'],
  ['tokyo', 'akita'],
  ['tokyo', 'seaofjapan'],
  ['tokyo', 'kyoto'],
  ['kyoto', 'tokyo'],
  ['kyoto', 'seaofjapan'],
  ['kyoto', 'kyushu'],
  ['kyushu', 'kyoto'],
  ['kyushu', 'yellowsea'],
  ['seaofjapan', 'kyoto'],
  ['seaofjapan', 'tokyo'],
  ['seaofjapan', 'akita'],
  ['seaofjapan', 'okhotsksea'],
  ['seaofjapan', 'southkorea'],
  ['seaofjapan', 'yellowsea'],
  ['yellowsea', 'shanghai'],
  ['yellowsea', 'mongolia'],
  ['yellowsea', 'northkorea'],
  ['yellowsea', 'southkorea'],
  ['yellowsea', 'seaofjapan'],
  ['yellowsea', 'kyushu'],
  ['yellowsea', 'formosa'],
  ['yellowsea', 'southchinasea'],
  ['peking', 'mongolia'],
  ['peking', 'shanghai'],
  ['peking', 'canton'],
  ['peking', 'sinkiang'],
  ['shanghai', 'mongolia'],
  ['shanghai', 'yellowsea'],
  ['shanghai', 'canton'],
  ['shanghai', 'peking'],
  ['canton', 'sinkiang'],
  ['canton', 'peking'],
  ['canton', 'shanghai'],
  ['canton', 'southchinasea'],
  ['canton', 'hongkong'],
  ['canton', 'tongking'],
  ['formosa', 'yellowsea'],
  ['tongking', 'canton'],
  ['tongking', 'southchinasea'],
  ['tongking', 'annam'],
  ['tongking', 'siam'],
  ['tongking', 'burma'],
  ['siam', 'tongking'],
  ['siam', 'annam'],
  ['siam', 'cambodia'],
  ['siam', 'malaysia'],
  ['annam', 'tongking'],
  ['annam', 'southchinasea'],
  ['annam', 'cambodia'],
  ['annam', 'cochin'],
  ['annam', 'siam'],
  ['cambodia', 'siam'],
  ['cambodia', 'annam'],
  ['cambodia', 'cochin'],
  ['cambodia', 'javasea'],
  ['cambodia', 'malaysia'],
  ['cochin', 'javasea'],
  ['cochin', 'cambodia'],
  ['cochin', 'annam'],
  ['malaysia', 'javasea'],
  ['malaysia', 'burma'],
  ['malaysia', 'siam'],
  ['malaysia', 'cambodia'],
  ['malaysia', 'bayofbengal'],
  ['hongkong', 'canton'],
  ['hongkong', 'southchinasea'],
  ['manila', 'southchinasea'],
  // This one is unclear from the map.
  ['manila', 'davao'],
  ['southchinasea', 'canton'],
  ['southchinasea', 'hongkong'],
  ['southchinasea', 'manila'],
  ['southchinasea', 'yellowsea'],
  ['southchinasea', 'javasea'],
  ['southchinasea', 'annam'],
  ['southchinasea', 'tongking'],
  ['southchinasea', 'timorsea'],
  // This one is unclear from the map.
  ['davao', 'manila'],
  ['davao', 'javasea'],
  ['javasea', 'davao'],
  ['javasea', 'sarawak'],
  ['javasea', 'borneo'],
  ['javasea', 'timorsea'],
  ['javasea', 'bayofbengal'],
  ['javasea', 'malaysia'],
  ['javasea', 'cambodia'],
  ['javasea', 'cochin'],
  ['javasea', 'southchinasea'],
  ['sumatra', 'indianocean'],
  ['sumatra', 'bayofbengal'],
  ['sumatra', 'timorsea'],
  ['sumatra', 'java'],
  ['sumatra', 'javasea'],
  ['java', 'indianocean'],
  ['java', 'timorsea'],
  ['java', 'sumatra'],
  ['sarawak', 'javasea'],
  ['sarawak', 'borneo'],
  ['borneo', 'sarawak'],
  ['borneo', 'javasea'],
  ['borneo', 'celebes'],
  ['celebes', 'borneo'],
  ['celebes', 'timorsea'],
  ['newguinea', 'timorsea'],
  ['timorsea', 'newguinea'],
  ['timorsea', 'java'],
  ['timorsea', 'sumatra'],
  ['timorsea', 'javasea'],
  ['timorsea', 'celebes'],
  ['timorsea', 'southchinasea'],
  ['timorsea', 'indianocean'],
];
export default new GameBoard({ nodes, edges });
