FROM ruby:3.2.2-slim
WORKDIR /app
RUN apt-get update -qq && apt-get install -y \
  libpq-dev \
  build-essential \
  nodejs \
  npm \
  yarn
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY package.json yarn.lock ./
RUN npm install -g yarn
RUN yarn install
COPY . .
EXPOSE 3000 3036
