version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  sidekiq:
    image: "723548248552.dkr.ecr.us-east-2.amazonaws.com/imperial:latest"
    command: bundle exec sidekiq -q default
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - redis
  
  webpacker:
    image: "723548248552.dkr.ecr.us-east-2.amazonaws.com/imperial:latest"
    command: /imperial/bin/webpack
    volumes:
      - .:/imperial

  web:
    image: "723548248552.dkr.ecr.us-east-2.amazonaws.com/imperial:latest"
    command: /bin/sh -c "sudo rm tmp/pids/server.pid && rails server -b 0.0.0.0 -p 80"
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_URL: ${DATABASE_URL}
      RAILS_SERVE_STATIC_FILES: enabled
    ports:
      - "80:80"
    volumes:
      - .:/imperial
    depends_on:
      - redis
      - webpacker
