services:
  app:
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
volumes:
  db-data:
    driver: local