FROM ruby:3.2.2-slim
WORKDIR /app
RUN apt-get update -qq && apt-get install -y \
  libpq-dev \
  nodejs \
  npm \
  yarn \
  && rm -rf /var/lib/apt/lists/*
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY package.json yarn.lock ./
RUN npm install -g yarn@1.22.21
RUN yarn install
COPY . .
RUN bundle exec ./bin/webpack
EXPOSE 3000
CMD ["rails", "s", "-b", "0.0.0.0"]