import { Nation } from "./constants.js";
import Action from "./action.js";
import setup from "./standardSetup.js";

export default [
  // setup
  Action.initialize({
    players: [
      { id: "Daniel", nation: Nation.RU },
      { id: "Claudia", nation: Nation.FR },
      { id: "Bert", nation: Nation.GB },
      { id: "Anton", nation: Nation.IT },
    ],
    setup,
  }),
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
  // first round
  Action.rondel({ nation: Nation.AH, cost: 0, slot: "import" }),
  Action.import([
    { province: "trieste", type: "fleet" },
    { province: "lemberg", type: "army" },
  ]),
  Action.noop,
  Action.rondel({ nation: Nation.IT, cost: 0, slot: "investor" }),
  Action.bondPurchase({ nation: Nation.GE, player: "Daniel", cost: 4 }),
  Action.rondel({ nation: Nation.FR, cost: 0, slot: "factory" }),
  Action.buildFactory({ province: "marseille" }),
  Action.rondel({ nation: Nation.GB, cost: 0, slot: "production1" }),
  Action.rondel({ nation: Nation.GE, cost: 0, slot: "production2" }),
  Action.rondel({ nation: Nation.RU, cost: 0, slot: "investor" }),
  Action.bondPurchase({ nation: Nation.GE, player: "Anton", cost: 6 }),
  // second round
  Action.rondel({ nation: Nation.AH, cost: 0, slot: "production2" }),
  Action.rondel({ nation: Nation.IT, cost: 0, slot: "production2" }),
  Action.rondel({ nation: Nation.FR, cost: 0, slot: "production1" }),
  Action.rondel({ nation: Nation.GB, cost: 0, slot: "maneuver1" }),
  Action.maneuver([
    {
      origin: "liverpool",
      destination: "north atlantic",
      nation: Nation.GB,
      type: "fleet",
    },
    {
      origin: "london",
      destination: "english channel",
      nation: Nation.GB,
      type: "fleet",
    },
  ]),
  Action.noop,
  Action.rondel({ nation: Nation.GE, cost: 0, slot: "maneuver2" }),
  Action.maneuver([
    {
      origin: "hamburg",
      destination: "north sea",
      nation: Nation.GE,
      type: "fleet",
    },
    {
      origin: "berlin",
      destination: "norway",
      nation: Nation.GE,
      type: "army",
    },
  ]),
  Action.rondel({ nation: Nation.RU, cost: 0, slot: "import" }),
  Action.import([
    { province: "st. petersburg", type: "fleet" },
    { province: "moscow", type: "army" },
    { province: "moscow", type: "army" },
  ]),
  Action.noop,
  Action.noop,
  // third round
  Action.rondel({ nation: Nation.AH, cost: 0, slot: "maneuver2" }),
  Action.maneuver([
    {
      origin: "trieste",
      destination: "ionian sea",
      nation: Nation.AH,
      type: "fleet",
    },
    {
      origin: "lemberg",
      destination: "romania",
      nation: Nation.AH,
      type: "army",
    },
    {
      origin: "budapest",
      destination: "west balkan",
      nation: Nation.AH,
      type: "army",
    },
    {
      origin: "vienna",
      destination: "tunis",
      nation: Nation.AH,
      type: "army",
    },
  ]),
  Action.noop,
  Action.noop,
  Action.noop,
  Action.rondel({ nation: Nation.IT, cost: 0, slot: "maneuver2" }),
  Action.maneuver([
    {
      origin: "naples",
      destination: "western mediterranean sea",
      nation: Nation.IT,
      type: "fleet",
    },
    {
      origin: "rome",
      destination: "spain",
      nation: Nation.IT,
      type: "army",
    },
  ]),
  Action.noop,
  Action.rondel({ nation: Nation.FR, cost: 0, slot: "maneuver1" }),
  Action.maneuver([
    {
      origin: "marseille",
      destination: "western mediterranean sea",
      nation: Nation.FR,
      type: "fleet",
    },
    {
      origin: "bordeaux",
      destination: "bay of biscay",
      nation: Nation.FR,
      type: "fleet",
    },
    {
      origin: "paris",
      destination: "morocco",
      nation: Nation.FR,
      type: "army",
    },
  ]),
  Action.noop,
  Action.noop,
  Action.fight({
    province: "western mediterranean sea",
    incumbent: Nation.IT,
    challenger: Nation.FR,
  }),
  Action.rondel({ nation: Nation.GB, cost: 0, slot: "investor" }),
  Action.bondPurchase({ nation: Nation.RU, player: "Bert", cost: 6 }),
  Action.rondel({ nation: Nation.GE, cost: 0, slot: "taxation" }),
  Action.rondel({ nation: Nation.RU, cost: 0, slot: "production2" }),
  // fourth round
  Action.rondel({ nation: Nation.AH, cost: 0, slot: "taxation" }),
  Action.rondel({ nation: Nation.IT, cost: 0, slot: "production1" }),
  Action.rondel({ nation: Nation.FR, cost: 0, slot: "production2" }),
  Action.bondPurchase({ nation: Nation.AH, player: "Claudia", cost: 6 }),
  Action.rondel({ nation: Nation.GB, cost: 0, slot: "production2" }),
  Action.rondel({ nation: Nation.GE, cost: 0, slot: "factory" }),
  Action.buildFactory({ province: "cologne" }),
  Action.rondel({ nation: Nation.RU, cost: 0, slot: "maneuver2" }),
  Action.maneuver([
    {
      origin: "st. petersburg",
      destination: "baltic sea",
      nation: Nation.RU,
      type: "fleet",
    },
    {
      origin: "odessa",
      destination: "black sea",
      nation: Nation.RU,
      type: "fleet",
    },
    {
      origin: "moscow",
      destination: "sweden",
      nation: Nation.RU,
      type: "army",
    },
    {
      origin: "moscow",
      destination: "turkey",
      nation: Nation.RU,
      type: "army",
    },
    {
      origin: "moscow",
      destination: "lemberg",
      nation: Nation.RU,
      type: "army",
    },
  ]),
  Action.noop,
  Action.noop,
  Action.noop,
  Action.noop,
];
