import { NationAsia } from './constants';
import GameBoard from './gameBoard';

const nodes = [
  { isOcean: true, name: 'arabiansea' },
  { isOcean: true, name: 'bayofbengal' },
  { isOcean: true, name: 'caspiansea' },
  { isOcean: true, name: 'indanocean' },
  { isOcean: true, name: 'javasea' },
  { isOcean: true, name: 'mediterraneansea' },
  { isOcean: true, name: 'okhotsksea' },
  { isOcean: true, name: 'seaofjapan' },
  { isOcean: true, name: 'southchinasea' },
  { isOcean: true, name: 'timorsea' },
  { isOcean: true, name: 'yellowsea' },
  { isOcean: false, name: 'budapest' },
  { isOcean: false, name: 'egypt' },
  { isOcean: false, name: 'sudan' },
  { isOcean: false, name: 'eastafrica' },
  { isOcean: false, name: 'arabia' },
  { isOcean: false, name: 'persia' },
  { isOcean: false, name: 'afghanistan' },
  { isOcean: false, name: 'nepal' },
  { isOcean: false, name: 'burma' },
  { isOcean: false, name: 'malaysia' },
  { isOcean: false, name: 'hongkong' },
  { isOcean: false, name: 'northkorea' },
  { isOcean: false, name: 'southkorea' },
  { isOcean: false, name: 'formosa' },
  { isOcean: false, name: 'manila' },
  { isOcean: false, name: 'davao' },
  { isOcean: false, name: 'newguinea' },
  {
    nation: NationAsia.TR, factoryType: 'shipyard', name: 'constantinople', egress: 'mediterraneansea',
  },
  { nation: NationAsia.TR, factoryType: 'armaments', name: 'angora' },
  {
    nation: NationAsia.TR,
    factoryType: 'armaments',
    name: 'syria',
    isHome: true,
  },
  { nation: NationAsia.TR, factoryType: 'armaments', name: 'armenia' },
  {
    nation: NationAsia.TR,
    factoryType: 'shipyard',
    name: 'iraq',
    isHome: true,
    egress: 'arabiansea',
  },
  {
    nation: NationAsia.RU,
    factoryType: 'shipyard',
    name: 'odessa',
    isHome: true,
    egress: 'mediterraneansea',
  },
  {
    nation: NationAsia.RU, factoryType: 'armaments', name: 'moscow', isHome: true,
  },
  { nation: NationAsia.RU, factoryType: 'armaments', name: 'omsk' },
  { nation: NationAsia.RU, factoryType: 'armaments', name: 'irkutsk' },
  {
    nation: NationAsia.RU,
    factoryType: 'shipyard',
    name: 'vladivostok',
    egress: 'okhotsksea',
  },
  {
    nation: NationAsia.CN,
    factoryType: 'shipyard',
    name: 'shanghai',
    egress: 'yellowsea',
  },
  {
    nation: NationAsia.CN,
    factoryType: 'armaments',
    name: 'canton',
  },
  {
    nation: NationAsia.CN,
    factoryType: 'armaments',
    name: 'peking',
    isHome: true,
  },
  {
    nation: NationAsia.CN, factoryType: 'armaments', name: 'sinkiang', isHome: true,
  },
  {
    nation: NationAsia.CN,
    factoryType: 'armaments',
    name: 'mongolia',
  },
  {
    nation: NationAsia.FR, factoryType: 'armaments', name: 'cambodia', isHome: true,
  },
  { nation: NationAsia.FR, factoryType: 'armaments', name: 'tongking' },
  {
    nation: NationAsia.FR,
    factoryType: 'shipyard',
    name: 'cochin',
    egress: 'javasea',
  },
  {
    nation: NationAsia.FR,
    factoryType: 'shipyard',
    name: 'annam',
    isHome: true,
    egress: 'southchinasea',
  },
  {
    nation: NationAsia.FR,
    factoryType: 'armaments',
    name: 'siam',
  },
  {
    nation: NationAsia.JP,
    factoryType: 'shipyard',
    name: 'kyoto',
    egress: 'seaofjapan',
  },
  {
    nation: NationAsia.JP,
    factoryType: 'shipyard',
    name: 'kyushu',
    egress: 'yellowsea',
  },
  { nation: NationAsia.JP, factoryType: 'armaments', name: 'akita' },
  {
    nation: NationAsia.JP, factoryType: 'shipyard', name: 'otaru', isHome: true, egress: 'okhotsksea',
  },
  {
    nation: NationAsia.JP,
    factoryType: 'shipyard',
    name: 'tokyo',
    isHome: true,
    egress: 'seaofjapan',
  },
  {
    nation: NationAsia.GB,
    factoryType: 'shipyard',
    name: 'madras',
    isHome: true,
    egress: 'indianocean',
  },
  {
    nation: NationAsia.GB, factoryType: 'armaments', name: 'hyderabad', isHome: true,
  },
  {
    nation: NationAsia.GB,
    factoryType: 'armaments',
    name: 'delhi',
  },
  {
    nation: NationAsia.GB, factoryType: 'shipyard', name: 'bengal', egress: 'bayofbengal',
  },
  {
    nation: NationAsia.GB, factoryType: 'shipyard', name: 'bombay', egress: 'arabaiansea',
  },
  {
    nation: NationAsia.GE,
    factoryType: 'shipyard',
    name: 'sumatra',
    isHome: true,
    egress: 'bayofbengal',
  },
  {
    nation: NationAsia.GE, factoryType: 'armaments', name: 'sarawak',
  },
  {
    nation: NationAsia.GE,
    factoryType: 'armaments',
    name: 'celebes',
  },
  {
    nation: NationAsia.GE, factoryType: 'shipyard', name: 'java', egress: 'indianocean',
  },
  {
    nation: NationAsia.GE, factoryType: 'shipyard', name: 'borneo', egress: 'javasea', isHome: true,
  },
];

const edges = [
  ['moscow', 'budapest'],
  ['moscow', 'odessa'],
  ['moscow', 'omsk'],
  ['budapest', 'moscow'],
  ['budapest', 'odessa'],
  ['budapest', 'constantinople'],
  ['budapest', 'mediterraneansea'],
  ['constantinople', 'budapest'],
  ['constantinople', 'mediterraneansea'],
  ['constantinople', 'angora'],
  ['mediterraneansea', 'constantinople'],
  ['mediterraneansea', 'budapest'],
  ['mediterraneansea', 'odessa'],
  ['mediterraneansea', 'armenia'],
  ['mediterraneansea', 'angora'],
  ['mediterraneansea', 'syria'],
  ['mediterraneansea', 'egypt'],
  ['egypt', 'mediterraneansea'],
  ['egypt', 'syria'],
  ['egypt', 'sudan'],
  ['egypt', 'arabiansea'],
  ['sudan', 'egypt'],
  ['sudan', 'eastafrica'],
  ['sudan', 'arabiansea'],
  ['odessa', 'moscow'],
  ['odessa', 'budapest'],
  ['odessa', 'mediterraneansea'],
  ['odessa', 'omsk'],
  ['odessa', 'armenia'],
  ['odessa', 'persia'],
];
export default new GameBoard({ nodes, edges });
