import { NationAsia } from './constants';
import GameBoard from './gameBoard';

const nodes = [
  { isOcean: true, name: 'arabiansea' },
  { isOcean: true, name: 'bayofbengal' },
  { isOcean: true, name: 'caspiansea' },
  { isOcean: true, name: 'indanocean' },
  { isOcean: true, name: 'javasea' },
  { isOcean: true, name: 'mediterraneansea' },
  { isOcean: true, name: 'okhotsksea' },
  { isOcean: true, name: 'seaofjapan' },
  { isOcean: true, name: 'southchinasea' },
  { isOcean: true, name: 'timorsea' },
  { isOcean: true, name: 'yellowsea' },
  { isOcean: false, name: 'budapest' },
  { isOcean: false, name: 'egypt' },
  { isOcean: false, name: 'sudan' },
  { isOcean: false, name: 'eastafrica' },
  { isOcean: false, name: 'arabia' },
  { isOcean: false, name: 'persia' },
  { isOcean: false, name: 'afghanistan' },
  { isOcean: false, name: 'nepal' },
  { isOcean: false, name: 'burma' },
  { isOcean: false, name: 'malaysia' },
  { isOcean: false, name: 'hongkong' },
  { isOcean: false, name: 'northkorea' },
  { isOcean: false, name: 'southkorea' },
  { isOcean: false, name: 'formosa' },
  { isOcean: false, name: 'manila' },
  { isOcean: false, name: 'davao' },
  { isOcean: false, name: 'newguinea' },
  {
    nation: NationAsia.TR, factoryType: 'shipyard', name: 'constantinople', egress: 'mediterraneansea',
  },
  { nation: NationAsia.TR, factoryType: 'armaments', name: 'angora' },
  {
    nation: NationAsia.TR,
    factoryType: 'armaments',
    name: 'syria',
    isHome: true,
  },
  { nation: NationAsia.TR, factoryType: 'armaments', name: 'armenia' },
  {
    nation: NationAsia.TR,
    factoryType: 'shipyard',
    name: 'iraq',
    isHome: true,
    egress: 'arabiansea',
  },
  {
    nation: NationAsia.RU,
    factoryType: 'shipyard',
    name: 'odessa',
    isHome: true,
    egress: 'mediterraneansea',
  },
  {
    nation: NationAsia.RU, factoryType: 'armaments', name: 'moscow', isHome: true,
  },
  { nation: NationAsia.RU, factoryType: 'armaments', name: 'omsk' },
  { nation: NationAsia.RU, factoryType: 'armaments', name: 'irkutsk' },
  {
    nation: NationAsia.RU,
    factoryType: 'shipyard',
    name: 'vladivostok',
    egress: 'okhotsksea',
  },
  {
    nation: NationAsia.CN,
    factoryType: 'shipyard',
    name: 'shanghai',
    egress: 'yellowsea',
  },
  {
    nation: NationAsia.CN,
    factoryType: 'armaments',
    name: 'canton',
  },
  {
    nation: NationAsia.CN,
    factoryType: 'armaments',
    name: 'peking',
    isHome: true,
  },
  {
    nation: NationAsia.CN, factoryType: 'armaments', name: 'sinkiang', isHome: true,
  },
  {
    nation: NationAsia.CN,
    factoryType: 'armaments',
    name: 'mongolia',
  },
  {
    nation: NationAsia.FR, factoryType: 'armaments', name: 'cambodia', isHome: true,
  },
  { nation: NationAsia.FR, factoryType: 'armaments', name: 'tongking' },
  {
    nation: NationAsia.FR,
    factoryType: 'shipyard',
    name: 'cochin',
    egress: 'javasea',
  },
  {
    nation: NationAsia.FR,
    factoryType: 'shipyard',
    name: 'annam',
    isHome: true,
    egress: 'southchinasea',
  },
  {
    nation: NationAsia.FR,
    factoryType: 'armaments',
    name: 'siam',
  },
  {
    nation: NationAsia.JP,
    factoryType: 'shipyard',
    name: 'kyoto',
    egress: 'seaofjapan',
  },
  {
    nation: NationAsia.JP,
    factoryType: 'shipyard',
    name: 'kyushu',
    egress: 'yellowsea',
  },
  { nation: NationAsia.JP, factoryType: 'armaments', name: 'akita' },
  {
    nation: NationAsia.JP, factoryType: 'shipyard', name: 'otaru', isHome: true, egress: 'okhotsksea',
  },
  {
    nation: NationAsia.JP,
    factoryType: 'shipyard',
    name: 'tokyo',
    isHome: true,
    egress: 'seaofjapan',
  },
  {
    nation: NationAsia.UK,
    factoryType: 'shipyard',
    name: 'madras',
    isHome: true,
    egress: 'indianocean',
  },
  {
    nation: NationAsia.UK, factoryType: 'armaments', name: 'hyderabad', isHome: true,
  },
  {
    nation: NationAsia.UK,
    factoryType: 'armaments',
    name: 'delhi',
  },
  {
    nation: NationAsia.UK, factoryType: 'shipyard', name: 'bengal', egress: 'bayofbengal',
  },
  {
    nation: NationAsia.UK, factoryType: 'shipyard', name: 'bombay', egress: 'arabaiansea',
  },
  {
    nation: NationAsia.GE,
    factoryType: 'shipyard',
    name: 'sumatra',
    isHome: true,
    egress: 'bayofbengal',
  },
  {
    nation: NationAsia.GE, factoryType: 'armaments', name: 'sarawak',
  },
  {
    nation: NationAsia.GE,
    factoryType: 'armaments',
    name: 'celebes',
  },
  {
    nation: NationAsia.GE, factoryType: 'shipyard', name: 'java', egress: 'indianocean',
  },
  {
    nation: NationAsia.GE, factoryType: 'shipyard', name: 'borneo', egress: 'javasea', isHome: true,
  },
];

const edges = [
  // ['moscow', 'kiev'],
  // ['moscow', 'warsaw'],
  // ['moscow', 'stpetersburg'],
  // ['warsaw', 'stpetersburg'],
  // ['warsaw', 'moscow'],
  // ['warsaw', 'kiev'],
  // ['warsaw', 'lemberg'],
  // ['warsaw', 'prague'],
  // ['warsaw', 'danzig'],
  // ['stpetersburg', 'moscow'],
  // ['stpetersburg', 'kiev'],
  // ['stpetersburg', 'warsaw'],
  // ['stpetersburg', 'danzig'],
  // ['stpetersburg', 'balticsea'],
  // ['kiev', 'moscow'],
  // ['kiev', 'odessa'],
  // ['kiev', 'romania'],
  // ['kiev', 'lemberg'],
  // ['kiev', 'warsaw'],
  // ['odessa', 'kiev'],
  // ['odessa', 'blacksea'],
  // ['odessa', 'romania'],
  // ['blacksea', 'odessa'],
  // ['blacksea', 'turkey'],
  // ['blacksea', 'easternmediterraneansea'],
  // ['blacksea', 'bulgaria'],
  // ['blacksea', 'romania'],
  // ['turkey', 'blacksea'],
  // ['turkey', 'easternmediterraneansea'],
  // ['turkey', 'bulgaria'],
  // ['easternmediterraneansea', 'turkey'],
  // ['easternmediterraneansea', 'ioniansea'],
  // ['easternmediterraneansea', 'greece'],
  // ['easternmediterraneansea', 'bulgaria'],
  // ['easternmediterraneansea', 'blacksea'],
  // ['bulgaria', 'romania'],
  // ['bulgaria', 'blacksea'],
  // ['bulgaria', 'turkey'],
  // ['bulgaria', 'easternmediterraneansea'],
  // ['bulgaria', 'greece'],
  // ['bulgaria', 'westbalkan'],
  // ['romania', 'lemberg'],
  // ['romania', 'kiev'],
  // ['romania', 'odessa'],
  // ['romania', 'blacksea'],
  // ['romania', 'bulgaria'],
  // ['romania', 'westbalkan'],
  // ['romania', 'budapest'],
  // ['westbalkan', 'budapest'],
  // ['westbalkan', 'romania'],
  // ['westbalkan', 'bulgaria'],
  // ['westbalkan', 'greece'],
  // ['westbalkan', 'ioniansea'],
  // ['westbalkan', 'trieste'],
  // ['greece', 'westbalkan'],
  // ['greece', 'bulgaria'],
  // ['greece', 'easternmediterraneansea'],
  // ['greece', 'ioniansea'],
  // ['ioniansea', 'trieste'],
  // ['ioniansea', 'westbalkan'],
  // ['ioniansea', 'greece'],
  // ['ioniansea', 'easternmediterraneansea'],
  // ['ioniansea', 'tunis'],
  // ['ioniansea', 'westernmediterraneansea'],
  // ['ioniansea', 'naples'],
  // ['lemberg', 'kiev'],
  // ['lemberg', 'romania'],
  // ['lemberg', 'budapest'],
  // ['lemberg', 'prague'],
  // ['lemberg', 'warsaw'],
  // ['budapest', 'lemberg'],
  // ['budapest', 'romania'],
  // ['budapest', 'westbalkan'],
  // ['budapest', 'trieste'],
  // ['budapest', 'vienna'],
  // ['budapest', 'prague'],
  // ['prague', 'danzig'],
  // ['prague', 'warsaw'],
  // ['prague', 'lemberg'],
  // ['prague', 'budapest'],
  // ['prague', 'vienna'],
  // ['prague', 'munich'],
  // ['prague', 'berlin'],
  // ['vienna', 'prague'],
  // ['vienna', 'budapest'],
  // ['vienna', 'trieste'],
  // ['vienna', 'venice'],
  // // ["vienna", "switzerland"],
  // ['vienna', 'munich'],
  // ['trieste', 'vienna'],
  // ['trieste', 'budapest'],
  // ['trieste', 'westbalkan'],
  // ['trieste', 'ioniansea'],
  // ['trieste', 'venice'],
  // ['venice', 'vienna'],
  // ['venice', 'trieste'],
  // ['venice', 'ioniansea'],
  // ['venice', 'rome'],
  // ['venice', 'florence'],
  // ['venice', 'genoa'],
  // ['rome', 'venice'],
  // ['rome', 'ioniansea'],
  // ['rome', 'naples'],
  // ['rome', 'westernmediterraneansea'],
  // ['rome', 'florence'],
  // ['naples', 'rome'],
  // ['naples', 'ioniansea'],
  // ['naples', 'westernmediterraneansea'],
  // ['florence', 'genoa'],
  // ['florence', 'venice'],
  // ['florence', 'rome'],
  // ['florence', 'westernmediterraneansea'],
  // // ["genoa", "switzerland"],
  // ['genoa', 'vienna'],
  // ['genoa', 'venice'],
  // ['genoa', 'florence'],
  // ['genoa', 'westernmediterraneansea'],
  // ['genoa', 'marseille'],
  // ['marseille', 'dijon'],
  // // ["marseille", "switzerland"],
  // ['marseille', 'genoa'],
  // ['marseille', 'westernmediterraneansea'],
  // ['marseille', 'spain'],
  // ['marseille', 'bordeaux'],
  // ['bordeaux', 'brest'],
  // ['bordeaux', 'dijon'],
  // ['bordeaux', 'marseille'],
  // ['bordeaux', 'spain'],
  // ['bordeaux', 'bayofbiscay'],
  // ['brest', 'englishchannel'],
  // ['brest', 'paris'],
  // ['brest', 'dijon'],
  // ['brest', 'bordeaux'],
  // ['brest', 'bayofbiscay'],
  // ['paris', 'englishchannel'],
  // ['paris', 'belgium'],
  // ['paris', 'dijon'],
  // ['paris', 'brest'],
  // ['dijon', 'paris'],
  // ['dijon', 'belgium'],
  // ['dijon', 'munich'],
  // // ["dijon", "switzerland"],
  // ['dijon', 'marseille'],
  // ['dijon', 'bordeaux'],
  // ['dijon', 'brest'],
  // ['tunis', 'westernmediterraneansea'],
  // ['tunis', 'algeria'],
  // ['algeria', 'westernmediterraneansea'],
  // ['algeria', 'tunis'],
  // ['algeria', 'morocco'],
  // ['morocco', 'bayofbiscay'],
  // ['morocco', 'algeria'],
  // ['westernmediterraneansea', 'marseille'],
  // ['westernmediterraneansea', 'genoa'],
  // ['westernmediterraneansea', 'florence'],
  // ['westernmediterraneansea', 'rome'],
  // ['westernmediterraneansea', 'naples'],
  // ['westernmediterraneansea', 'ioniansea'],
  // ['westernmediterraneansea', 'tunis'],
  // ['westernmediterraneansea', 'algeria'],
  // ['westernmediterraneansea', 'bayofbiscay'],
  // ['westernmediterraneansea', 'spain'],
  // ['spain', 'bayofbiscay'],
  // ['spain', 'bordeaux'],
  // ['spain', 'marseille'],
  // ['spain', 'westernmediterraneansea'],
  // ['spain', 'portugal'],
  // ['portugal', 'bayofbiscay'],
  // ['portugal', 'spain'],
  // ['bayofbiscay', 'northatlantic'],
  // ['bayofbiscay', 'englishchannel'],
  // ['bayofbiscay', 'brest'],
  // ['bayofbiscay', 'bordeaux'],
  // ['bayofbiscay', 'spain'],
  // ['bayofbiscay', 'portugal'],
  // ['bayofbiscay', 'morocco'],
  // ['northatlantic', 'dublin'],
  // ['northatlantic', 'edinburgh'],
  // ['northatlantic', 'northsea'],
  // ['northatlantic', 'liverpool'],
  // ['northatlantic', 'london'],
  // ['northatlantic', 'englishchannel'],
  // ['northatlantic', 'bayofbiscay'],
  // ['dublin', 'northatlantic'],
  // ['edinburgh', 'northatlantic'],
  // ['edinburgh', 'northsea'],
  // ['edinburgh', 'sheffield'],
  // ['edinburgh', 'liverpool'],
  // ['liverpool', 'edinburgh'],
  // ['liverpool', 'sheffield'],
  // ['liverpool', 'london'],
  // ['liverpool', 'northatlantic'],
  // ['sheffield', 'edinburgh'],
  // ['sheffield', 'northsea'],
  // ['sheffield', 'london'],
  // ['sheffield', 'liverpool'],
  // ['london', 'sheffield'],
  // ['london', 'northsea'],
  // ['london', 'englishchannel'],
  // ['london', 'northatlantic'],
  // ['london', 'liverpool'],
  // ['northsea', 'norway'],
  // ['northsea', 'balticsea'],
  // ['northsea', 'denmark'],
  // ['northsea', 'hamburg'],
  // ['northsea', 'holland'],
  // ['northsea', 'englishchannel'],
  // ['northsea', 'london'],
  // ['northsea', 'sheffield'],
  // ['northsea', 'edinburgh'],
  // ['northsea', 'northatlantic'],
  // ['englishchannel', 'northatlantic'],
  // ['englishchannel', 'london'],
  // ['englishchannel', 'holland'],
  // ['englishchannel', 'belgium'],
  // ['englishchannel', 'paris'],
  // ['englishchannel', 'brest'],
  // ['englishchannel', 'bayofbiscay'],
  // ['belgium', 'englishchannel'],
  // ['belgium', 'holland'],
  // ['belgium', 'cologne'],
  // ['belgium', 'munich'],
  // ['belgium', 'dijon'],
  // ['belgium', 'paris'],
  // ['holland', 'northsea'],
  // ['holland', 'hamburg'],
  // ['holland', 'cologne'],
  // ['holland', 'belgium'],
  // ['holland', 'englishchannel'],
  // ['cologne', 'belgium'],
  // ['cologne', 'holland'],
  // ['cologne', 'hamburg'],
  // ['cologne', 'berlin'],
  // ['cologne', 'munich'],
  // ['munich', 'cologne'],
  // ['munich', 'berlin'],
  // ['munich', 'prague'],
  // ['munich', 'vienna'],
  // // ["munich", "switzerland"],
  // ['munich', 'dijon'],
  // ['munich', 'belgium'],
  // ['berlin', 'balticsea'],
  // ['berlin', 'danzig'],
  // ['berlin', 'prague'],
  // ['berlin', 'munich'],
  // ['berlin', 'cologne'],
  // ['berlin', 'hamburg'],
  // ['hamburg', 'denmark'],
  // ['hamburg', 'balticsea'],
  // ['hamburg', 'berlin'],
  // ['hamburg', 'cologne'],
  // ['hamburg', 'holland'],
  // ['hamburg', 'northsea'],
  // ['danzig', 'balticsea'],
  // ['danzig', 'stpetersburg'],
  // ['danzig', 'warsaw'],
  // ['danzig', 'prague'],
  // ['danzig', 'berlin'],
  // ['norway', 'northsea'],
  // ['norway', 'balticsea'],
  // ['norway', 'sweden'],
  // ['sweden', 'norway'],
  // ['sweden', 'balticsea'],
  // ['balticsea', 'stpetersburg'],
  // ['balticsea', 'danzig'],
  // ['balticsea', 'berlin'],
  // ['balticsea', 'hamburg'],
  // ['balticsea', 'denmark'],
  // ['balticsea', 'northsea'],
  // ['balticsea', 'sweden'],
];

export default new GameBoard({ nodes, edges });
