# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v18
        with:
          skip_annotations: true
          file_extensions: |
            **/*.js
            **/*.vue
      - run: npm test
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
